In [1]:
import pandas as pd

df = pd.read_pickle('./df_attack_combined.pkl')


In [2]:
df = df.drop([' Label'], axis =1)

X = df.iloc[:, df.columns != 'Class']
y = df.iloc[:, df.columns == 'Class']

from sklearn import preprocessing


min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(X)
X_undersample_Norm = pd.DataFrame(x_scaled)

In [3]:
from sklearn.model_selection import train_test_split

# Undersampled dataset
X_train, X_test, y_train, y_test = train_test_split(x_scaled,y,test_size = 0.2,random_state = 0)
print("")
print("Rows in training undersample dataset: ", len(X_train))
print("Rows in test undersample dataset: ", len(X_test))
print("Total number: ", len(X_train)+len(X_test))


Rows in training undersample dataset:  445244
Rows in test undersample dataset:  111312
Total number:  556556


In [5]:
y_train

Class
183318     DoS/DDoS
221516     PortScan
275089     PortScan
133110     DoS/DDoS
43384      DoS/DDoS
212223     PortScan
286602     DoS/DDoS
125525     DoS/DDoS
215985     DoS/DDoS
253640     DoS/DDoS
205799     DoS/DDoS
177420     PortScan
166118     DoS/DDoS
177641     DoS/DDoS
264880     DoS/DDoS
118465     DoS/DDoS
166036     DoS/DDoS
148846     DoS/DDoS
63610      DoS/DDoS
194533  Brute Force
115953     PortScan
292145     DoS/DDoS
138707     PortScan
301243     DoS/DDoS
156000     PortScan
116468     PortScan
158170     DoS/DDoS
155675     DoS/DDoS
160657     PortScan
288173     DoS/DDoS
...             ...
287259     DoS/DDoS
377656  Brute Force
143939     DoS/DDoS
133384     DoS/DDoS
143629     PortScan
188912     DoS/DDoS
242383     DoS/DDoS
84874      DoS/DDoS
192575     PortScan
685855     DoS/DDoS
132497     DoS/DDoS
207369     DoS/DDoS
106256     DoS/DDoS
306457     DoS/DDoS
196292     DoS/DDoS
91949      DoS/DDoS
219122     PortScan
132631     DoS/DDoS
323892     DoS/DDoS
130476     PortScan
69392      DoS/DDoS
136611     DoS/DDoS
215020     DoS/DDoS
189347     DoS/DDoS
404794  Brute Force
120870     DoS/DDoS
111956     PortScan
181881     DoS/DDoS
201508     DoS/DDoS
33750      DoS/DDoS

[445244 rows x 1 columns]

In [51]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,precision_recall_curve,auc,roc_auc_score,roc_curve,recall_score,classification_report,accuracy_score 
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train,y_train)
y_pred = neigh.predict(X_test)
cnf_matrix = confusion_matrix(y_test,y_pred)

C:\Users\tyagi\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


In [52]:
for i in cnf_matrix:
    print(i)

[385   0   0   0   0   0]
[   1 2780    4    0    0    0]
[    1     0 76061     0     1     2]
[0 0 1 3 0 0]
[    0     0     7     0 31614     0]
[  0   5   8   0   2 437]


In [53]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9997125197642662

In [54]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='weighted') 

0.999710795689818

In [ ]:
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
grid={"C":np.logspace(-1,2,1), "penalty":["l1","l2"]}# l1 lasso l2 ridge
LR=LogisticRegression()
LR_C=GridSearchCV(LR,grid,cv=2)
LR_C.fit(X_train,y_train)
c_value = LR_C.best_params_['C']
penalty_value = LR_C.best_params_['penalty']

print ("tuned hpyerparameters :(best parameters) ",LR_C.best_params_)
print ("accuracy :",LR_C.best_score_)

In [55]:
from sklearn.cross_validation import KFold, cross_val_score
from sklearn.metrics import confusion_matrix,precision_recall_curve,auc,roc_auc_score,roc_curve,recall_score,classification_report,accuracy_score 
lr = LogisticRegression(C = 0.1, penalty = 'l1')
lr.fit(X_train,y_train)
y_pred_undersample = lr.predict(X_test)


C:\Users\tyagi\Anaconda3\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [56]:

cnf_matrix = confusion_matrix(y_test,y_pred_undersample)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_undersample)


0.9951847060514589

In [57]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred_undersample, average='weighted') 

C:\Users\tyagi\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.9951150903309514

In [58]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)

In [59]:
y_pred = clf.predict(X_test)

In [60]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9997304872789996

In [61]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='weighted') 

0.9997291375476492

In [62]:
from sklearn.preprocessing import LabelBinarizer
encoder = LabelBinarizer()
transfomed_label = encoder.fit_transform(y)
print(transfomed_label)

from sklearn.model_selection import train_test_split

# Undersampled dataset
X_train, X_test, y_train, y_test = train_test_split(x_scaled,transfomed_label,test_size = 0.2,random_state = 0)
print("")
print("Rows in training undersample dataset: ", len(X_train))
print("Rows in test undersample dataset: ", len(X_test))
print("Total number: ", len(X_train)+len(X_test))

[[0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 ...
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]]

Rows in training undersample dataset:  445244
Rows in test undersample dataset:  111312
Total number:  556556


In [63]:
from keras.utils import to_categorical
from keras import models
from keras import layers
from keras.datasets import imdb
from keras.callbacks import EarlyStopping


early_stopping_monitor = EarlyStopping(patience=3)

model = models.Sequential()
# Input - Layer
model.add(layers.Dense(78, activation = "relu", input_shape=(78, )))
# Hidden - Layers
model.add(layers.Dropout(0.3, noise_shape=None, seed=None))
model.add(layers.Dense(200, activation = "relu"))
model.add(layers.Dropout(0.3, noise_shape=None, seed=None))
model.add(layers.Dense(200, activation = "relu"))
model.add(layers.Dropout(0.2, noise_shape=None, seed=None))
model.add(layers.Dense(200, activation = "relu"))
model.add(layers.Dropout(0.3, noise_shape=None, seed=None))
model.add(layers.Dense(200, activation = "relu"))
model.add(layers.Dropout(0.2, noise_shape=None, seed=None))
model.add(layers.Dense(78, activation = "relu"))
# Output- Layer
model.add(layers.Dense(6, activation = "sigmoid"))
model.summary()
# compiling the model
model.compile(
 optimizer = "adam",
 loss = "binary_crossentropy",
 metrics = ["accuracy"]
)


results = model.fit(
 X_train, y_train,
 epochs= 50,
 batch_size = 100,
 validation_data = (X_test, y_test),callbacks=[early_stopping_monitor]
)
print("Test-Accuracy:", np.mean(results.history["val_acc"]))

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_78 (Dense)             (None, 78)                6162      
_________________________________________________________________
dropout_48 (Dropout)         (None, 78)                0         
_________________________________________________________________
dense_79 (Dense)             (None, 200)               15800     
_________________________________________________________________
dropout_49 (Dropout)         (None, 200)               0         
_________________________________________________________________
dense_80 (Dense)             (None, 200)               40200     
_________________________________________________________________
dropout_50 (Dropout)         (None, 200)               0         
_________________________________________________________________
dense_81 (Dense)             (None, 200)               40200     
__________

In [69]:
from sklearn.externals import joblib
filename = 'phase2_tree.sav'
joblib.dump(clf, filename)

['phase2_tree.sav']